init/unix.sh, init/windows.ps1
Appearently, PowerShell does not have a way to stream its feedbacks to the main terminal while the binary execution output important data like progress status and graphics card information. Hence, we don't have a choice but to let it open a new window every single time. Let's fix it.
This patch fixed a non-responsive UI bug in windows' execution inside init/ directory.
=> init: fixed non-repsonsive UI bug in windows' execution

.configs/monteur/clean/jobs/build-log.toml, .configs/monteur/clean/jobs/build-tmp.toml, .configs/monteur/clean/jobs/compose-log.toml, .configs/monteur/clean/jobs/compose-tmp.toml, .configs/monteur/clean/jobs/hestiaDOCS.toml, .configs/monteur/clean/jobs/package-log.toml, .configs/monteur/clean/jobs/package-tmp.toml, .configs/monteur/clean/jobs/prepare-log.toml, .configs/monteur/clean/jobs/prepare-tmp.toml, .configs/monteur/clean/jobs/publish-log.toml, .configs/monteur/clean/jobs/publish-tmp.toml, .configs/monteur/clean/jobs/release-log.toml, .configs/monteur/clean/jobs/releases.toml, .configs/monteur/clean/jobs/setup-log.toml, .configs/monteur/clean/jobs/setup-tmp.toml, .configs/monteur/clean/jobs/test-log.toml, .configs/monteur/clean/jobs/test-tmp.toml
Since the ZORALab's Monteur is ready, we can proceed to add clean up CI jobs into it. Hence, let's do this.
This patch adds repo clean up CI jobs in .configs/monteur/ directory.
=> .configs/monteur: added repo clean up CI jobs

.configs/monteur/release/jobs/archive.toml
Since the zoralab's Monteur is ready, we can proceed to add the release CI job in. Hence, let's do this.
This patch adds release CI job in .configs/monteur/ directory.
=> .configs/monteur: added release CI job

README.md
The current installation instructions are way too outdated especially when we are moving to release packages instead of asking users to git clone everything. Hence, let's update it.
This patch updates installation instructions in README.md.
=> README.md: updated installation instructions

README.md
There was a typo in the previous patch for installation instruction. Hence, we need to correct it.
This patch corrects typo in README.md.
=> README.md: corrected typo

start.cmd
For some reason, commit d64c62f5de7f5f55c87432de601d688f11d144fe accidentally removed the bypass execution policy causing an immediate denial of use in new Windows system. Hence, we need to restore it back.
This patch restores and fixes execution policy restriction due to accidental removal in the previous patch.
Reported-by: Shuralyov, Jean <jean.shuralyov@proton.me>
=> start.cmd: fixed execution policy restriction due to accidental removal.

README.md
Jean discovered that the binary depends on an external MSFT C++ dependency on a clean slate laptop. We did not discover it before since this dependency is usually installed automatically by other software using it. Hence, let's add a note into the README.md.
This patch adds MSFT C++ dependency notice into README.md.
Reported-by: Joly0 <13993216+Joly0@users.noreply.github.com>
=> README.md: added MSFT C++ dependency notice

models/upscayl-uniscale-restore.param, models/upscayl-uniscale-restore.sh
Upscayl team uploaded a uniscale-restore AI model in their custom-models repo (https://github.com/upscayl/custom-models) with a compatible license. Hence, we should integrate it. Let's do this.
This patch adds upscayl-uniscale-restore AI model into models/ directory.
=> models: added upscayl-uniscale-restore AI model

init/unix.sh, tests/benchmark.cmd
Since there are demands for controlled parallel processing, we should implement the feature. Hence, let's start with the UNIX system first.
This patch upgrades unix.sh to permit controlled parallel processing in init/ directory.
=> init: upgraded unix.sh to allow parallel processing

init/unix.sh
Since we are not meddling with audio at all, we should its entire data processor away from our implementations for percise performance. Hence, let's remove it.
This patch removes unused audio_codec data processor from init/unit.sh file.
=> init: removed unused audio_codec from data processor

models/upscayl-nmkd-4x-superscale-sd-178000-g.param, models/upscayl-nmkd-4x-superscale-sd-178000-g.sh
Upscayl's team added a new model called
"4x_NMKD-Superscale-SP_178000_G". Let's port it in.
This patch adds upscayl-nmkd-4x-superscale-sd-178000-g into models/ directory.
=> models: added upscayl-nmkd-4x-superscale-sd-178000-g

models/upscayl-nomos-4x-8k-sc.param, models/upscayl-nomos-4x-8k-sc.sh
Upscayl's team released a new "upscayl-nomos-4x-8k-sc" model. Hence, let's pull the update from the upstream.
This patch adds upscayl-nomos-4x-8k-sc into models/ directory.
=> models: added upscayl-nomos-4x-8k-sc

models/upscayl-hfa2k.param, models/upscayl-hfa2k.sh
Upscayl team uploaded a new model called 'HFA2k'. Hence, let's port it from upstream.
This patch adds upscayl-hfa2k into models/ directory.
=> models: added upscayl-hfa2k

init/services/compilers/upscaler.ps1, init/services/compilers/upscaler.sh, init/services/i18n/error-unsupported.ps1, init/services/i18n/error-unsupported.sh, init/services/io/os.sh, init/start.ps1, init/start.sh
To make sure the upscaler's host system is checked before execution, it's best we port the OS + Arch system verifications into the new scripting libraries. Hence, let's do this.
This patch adds upscaler's host system verification into the init/ directory.
=> init: added upscaler's host system verification

init/services/i18n/error-input-unknown.ps1, init/services/i18n/error-input-unknown.sh, init/services/i18n/error-input-unsupported.ps1, init/services/i18n/error-input-unsupported.sh, init/services/io/fs.ps1, init/services/io/fs.sh, init/start.ps1, init/start.sh, tests/01_test_upscale_image_single.sh.ps1
Since we need to make sure the input is actually a valid one, we should proceed to add its validator in. Hence, let's do this.
This patch adds input target validator into init/ directory.
=> init: added input target validator

init/services/i18n/help.ps1
It appears the Powershell version of printout is ugly. Hence, let's clean it up.
This patch cleans up help printout for PowerShell side in init/ directory.
=> init: clean up help printout for PowerShell

init/services/i18n/error-parallel-unsupported.ps1, init/services/i18n/error-parallel-unsupported.sh, init/start.ps1, init/start.sh, tests/01_test_upscale_image_single.sh.ps1
Since we want to support parallel processing from the get-go, we have to supply its validator. Hence, let's do this.
This patch adds parallelism count support into init/ directory.
=> init: added parallelism count support

init/services/compilers/upscaler.ps1, init/services/compilers/upscaler.sh, init/services/i18n/error-format-unsupported.ps1, init/services/i18n/error-format-unsupported.sh, init/start.ps1, init/start.sh
Since the output format is selectable, we have to add its validator function. Let's do this.
This patcha dds format validator into init/ directory.
=> init: added format validator

init/services/compilers/upscaler.ps1, init/services/compilers/upscaler.sh
There was an error determining the output path where if the given path is only a filepath (without directory), the program will try to use the original input filename as a directory and cause the upscaling process to be unreasonably failed. Hence, we need to fix this bug.
This patch fixes the output path determination error in init/ directory.
=> init: fixed output path determination error

init/unix.sh
fix issue when creating directory where input file of a video is in the same directory to output and has relative path.
Given:
/usr/bin/upscaler --model upscayl-ultrasharp \
--scale 2 \
--format png \
--video \
--input my-video.mp4 \
--output my-video-upscaled
The program tries to create a directory ./my-video.mp4/something/something throws an error and stop the execution
This fix uses "my-video" instead of "my-video.mp4" as subject dir if subject_dir is equal to input.
=> unix.sh - fix mkdir issue

init/services/HestiaOS/Exec.ps1, init/services/HestiaOS/Exec.sh, init/services/HestiaOS/Get_Arch.ps1, init/services/HestiaOS/Get_Arch.sh, init/services/HestiaOS/Is_Command_Available.ps1, init/services/HestiaOS/Is_Command_Available.sh, init/services/HestiaOS/Is_Simulation_Mode.ps1, init/services/HestiaOS/Is_Simulation_Mode.sh, init/services/HestiaOS/Is_Variable_Set.ps1, init/services/HestiaOS/Is_Variable_Set.sh, init/services/HestiaOS/To_Arch.ps1, init/services/HestiaOS/To_Arch.sh, init/services/HestiaOS/To_Arch_MSFT.ps1, init/services/HestiaOS/To_Arch_MSFT.sh, init/services/HestiaOS/To_Arch_UNIX.ps1, init/services/HestiaOS/To_Arch_UNIX.sh, init/services/HestiaOS/To_OS.ps1, init/services/HestiaOS/To_OS.sh, init/services/HestiaOS/Vanilla.sh.ps1
Since the latest implementations are using Hestia library, it's better to port them. Let's deal with HestiaOS library.
This patch ports HestiaOS library in init/ directory.
=> init: ported HestiaOS library

init/services/HestiaKERNEL/Is_Unicode.ps1, init/services/HestiaKERNEL/Is_Unicode.sh, init/services/HestiaKERNEL/Unicode.ps1, init/services/HestiaKERNEL/Unicode.sh, init/services/HestiaKERNEL/Vanilla.sh.ps1
Since there are multiple level-2 Hestia libraries use string functions and they can't perform diamond import, it's best to port those fundamentals into HestiaKERNEL library. Hence, let's do this.
This patch ports string fundamentals into HestiaKERNEL library in init/ directory.
=> init: ported string fundamentals into HestiaKERNEL library

init/services/HestiaKERNEL/To_Unicode_From_String.ps1, init/services/HestiaKERNEL/To_Unicode_From_String.sh, init/services/HestiaKERNEL/Unicode.ps1, init/services/HestiaKERNEL/Vanilla.sh.ps1
Since case changing functions are required for all level-2 libraries, we have to start from the beginning. Let's port the To_Unicode_From_String primitive function into HestiaKERNEL library.
This patch ports To_Unicode_From_String primitive function into HestiaKERNEL library in init/ directory.
=> init: ported To_Unicode_From_String primitive function

init/services/HestiaKERNEL/To_UTF8_From_Unicode.ps1, init/services/HestiaKERNEL/To_UTF8_From_Unicode.sh, init/services/HestiaKERNEL/Vanilla.sh.ps1
Since other level-2 libraries depends on some primitive string functions, we have to to port the To_UTF8_From_Unicode one. Hence, let's do this.
This patch ports To_UTF8_From_Unicode primitive function into HestiaKERNEL in init/ directory.
=> init: ported To_UTF8_From_Unicode primitive function

init/services/HestiaKERNEL/To_UTF16_From_Unicode.ps1, init/services/HestiaKERNEL/To_UTF16_From_Unicode.sh
Since a number of level 2 libraries need some basic string processing function, we have to port them into HestiaKERNEL. Hence, let's do for To_UTF16_From_Unicode function.
This patch ports To_UTF16_From_Unicode primitive function into init/ directory.
=> init: ported To_UTF16_From_Unicode primitive function

init/services/HestiaKERNEL/To_UTF32_From_Unicode.ps1, init/services/HestiaKERNEL/To_UTF32_From_Unicode.sh, init/services/HestiaKERNEL/Vanilla.sh.ps1
Since there are a number of level-2 libraries are using some string functions, we have to port them into HestiaKERNEL library.
This patch ports To_UTF32_From_Unicode primitive function into init/ directory.
=> init: ported To_UTF32_From_Unicode primitive function

init/services/HestiaKERNEL/Vanilla.sh.ps1
It appears it was a miss during the last porting. Hence, let's export that function.
This patch exports To_UTF16_From_Unicode primitive function in init/ directory.
=> init: exported To_UTF16_From_Unicode primitive function

init/services/HestiaKERNEL/Get_String_Encoder.ps1, init/services/HestiaKERNEL/Get_String_Encoder.sh, init/services/HestiaKERNEL/Unicode.ps1, init/services/HestiaKERNEL/Vanilla.sh.ps1
Since level-2 libraries use certain string functions, we have to port their primitive functions into HestiaKERNEL. Hence, let's do this.
This patch ports Get_String_Encoder primitive function into init/ directory.
=> init: ported Get_String_Encoder primitive function

init/services/HestiaKERNEL/Endian.ps1, init/services/HestiaKERNEL/Endian.sh, init/services/HestiaKERNEL/To_String_From_Unicode.ps1, init/services/HestiaKERNEL/To_String_From_Unicode.sh, init/services/HestiaKERNEL/To_UTF16_From_Unicode.ps1, init/services/HestiaKERNEL/To_UTF16_From_Unicode.sh, init/services/HestiaKERNEL/To_UTF32_From_Unicode.ps1, init/services/HestiaKERNEL/To_UTF32_From_Unicode.sh, init/services/HestiaKERNEL/To_UTF8_From_Unicode.ps1, init/services/HestiaKERNEL/To_UTF8_From_Unicode.sh, init/services/HestiaKERNEL/Unicode.ps1, init/services/HestiaKERNEL/Vanilla.sh.ps1
Since level 2 libraries need a certain string processing function, we got to port the primitive functions into HestiaKERNEL. Hence, let's deal with To_String_From_Unicode function.
This patch ports To_String_From_Unicode primitive function in init/ directory.
=> init: ported To_String_From_Unicode primitive function

init/services/HestiaKERNEL/Is_Unicode.sh, init/services/HestiaKERNEL/To_Lowercase_String.sh, init/services/HestiaKERNEL/To_String_From_Unicode.sh, init/services/HestiaKERNEL/To_Titlecase_String.sh, init/services/HestiaKERNEL/Trim_Left_String.ps1, init/services/HestiaKERNEL/Trim_Left_String.sh, init/services/HestiaKERNEL/Trim_Left_Unicode.ps1, init/services/HestiaKERNEL/Trim_Left_Unicode.sh, init/services/HestiaKERNEL/Vanilla.sh.ps1, init/start.ps1, init/start.sh
Since Level 1 Hestia libraries requires a number of string processing functions, we have to port the Trim_Left primitive functions into HestiaKERNEL library. Hence, let's do this.
This patch ports Trim_Left_{String,Unicode} primitive function into init/ directory.
=> init: ported Trim_Left_{String,Unicode} primitive function

init/services/HestiaKERNEL/Trim_Right_String.ps1, init/services/HestiaKERNEL/Trim_Right_String.sh, init/services/HestiaKERNEL/Trim_Right_Unicode.ps1, init/services/HestiaKERNEL/Trim_Right_Unicode.sh, init/services/HestiaKERNEL/Vanilla.sh.ps1, init/start.ps1, init/start.sh
This patch ports Trim_Right_{String,Unicode} primitive function into HestiaKERNEL library in init/ directory.
=> init: Trim_Right_{String,Unicode} primitive function

init/services/HestiaKERNEL/Get_First_Character.ps1, init/services/HestiaKERNEL/Get_First_Character.sh, init/services/HestiaKERNEL/Get_First_Unicode.ps1, init/services/HestiaKERNEL/Get_First_Unicode.sh, init/services/HestiaKERNEL/Unicode.ps1, init/services/HestiaKERNEL/Unicode.sh, init/start.ps1, init/start.sh
This patch ports Get_First_{Char,Unicode} primitive function into HestiaKERNEL library in init/ directory.
=> init: ported Get_First_{String,Unicode} primitive function

init/services/HestiaKERNEL/String/Get_Length_String.ps1, init/services/HestiaKERNEL/String/Get_Length_String.sh, init/services/HestiaKERNEL/Unicode/Get_Length_Unicode.ps1, init/services/HestiaKERNEL/Unicode/Get_Length_Unicode.sh, init/start.ps1, init/start.sh
This patch ports Get_Length_{String,Unicode} primitive function into HestiaKERNEL library in init/ directory.
=> init: ported Get_Length_{String,Unicode} primitive functions

init/services/HestiaKERNEL/String/Trim_Prefix_String.ps1, init/services/HestiaKERNEL/String/Trim_Prefix_String.sh, init/services/HestiaKERNEL/Unicode/Trim_Prefix_Unicode.ps1, init/services/HestiaKERNEL/Unicode/Trim_Prefix_Unicode.sh, init/start.ps1, init/start.sh
This patch ports Get_Prefix_{String,Unicode} primitive function into HestiaKERNEL library in init/ directory.
=> init: ported Trim_Prefix_{String,Unicode} primitive function

init/services/HestiaKERNEL/String/Trim_Whitespace_Left_String.ps1, init/services/HestiaKERNEL/String/Trim_Whitespace_Left_String.sh, init/services/HestiaKERNEL/Unicode/Trim_Whitespace_Left_Unicode.ps1, init/services/HestiaKERNEL/Unicode/Trim_Whitespace_Left_Unicode.sh, init/services/HestiaKERNEL/Vanilla.sh.ps1, init/start.ps1, init/start.sh
This patch ports Trim_Whitespace_Left_{String,Unicode} primitive function into HestiaKERNEL library in init/ directory.
=> init: ported Trim_Whitespace_Left_{String,Unicode} primitive function

init/services/HestiaKERNEL/String/Trim_Whitespace_Right_String.ps1, init/services/HestiaKERNEL/String/Trim_Whitespace_Right_String.sh, init/services/HestiaKERNEL/Unicode/Trim_Whitespace_Right_Unicode.ps1, init/services/HestiaKERNEL/Unicode/Trim_Whitespace_Right_Unicode.sh, init/services/HestiaKERNEL/Vanilla.sh.ps1, init/start.ps1, init/start.sh
This patch ports Trim_Whitespace_Right_{String,Unicode} primitive function into HestiaKERNEL library in init/ directory.
=> init: ported Trim_Whitespace_Right_{String,Unicode} primitive function

init/services/HestiaKERNEL/String/Trim_Whitespace_String.ps1, init/services/HestiaKERNEL/String/Trim_Whitespace_String.sh, init/services/HestiaKERNEL/Unicode/Trim_Whitespace_Unicode.ps1, init/services/HestiaKERNEL/Unicode/Trim_Whitespace_Unicode.sh, init/services/HestiaKERNEL/Vanilla.sh.ps1, init/start.ps1, init/start.sh
This patch ports Trim_Whitespace_{String,Unicode} primitive function into HestiaKERNEL library in init/ directory.
=> init: ported Trim_Whitespace_{String,Unicode} primitive function

init/services/HestiaKERNEL/Unicode/To_UTF32_From_Unicode.ps1, init/services/HestiaKERNEL/Unicode/To_UTF32_From_Unicode.sh, init/start.ps1, init/start.sh
There were some minor performance bugs from To_UTF32_From_Unicode primitive function. Hence, let's fix it.
This patch fixes To_UTF32_From_Unicode primitive function bug in init/ directory.
=> init: fixed To_UTF32_From_Unicode primitive function bug

init/services/HestiaKERNEL/Unicode/To_UTF32_From_Unicode.ps1, init/services/HestiaKERNEL/Unicode/To_UTF32_From_Unicode.sh, init/services/HestiaKERNEL/Unicode/To_UTF8_From_Unicode.ps1, init/services/HestiaKERNEL/Unicode/To_UTF8_From_Unicode.sh
There were some minor performance bugs from To_UTF8_From_Unicode primitive function. Hence, let's fix it.
This patch fixes To_UTF8_From_Unicode primitive function bug in init/ directory.
=> init: fixed To_UTF8_From_Unicode primitive function bug

init/services/HestiaKERNEL/String/To_Titlecase_String.sh
There were some minor performance bugs from To_Titlecase_String primitive function. Hence, let's fix it.
This patch fixes To_Titlecase_String primitive function bug in init/ directory.
=> init: fixed To_Titlecase_String primitive function bug

init/services/HestiaKERNEL/String/To_Lowercase_String.sh
There were some minor performance bugs from To_Lowercase_String primitive function. Hence, let's fix it.
This patch fixes To_Lowercase_String primitive function bug in init/ directory.
=> init: fixed To_Lowercase_String primitive function bug

init/services/HestiaKERNEL/String/To_Uppercase_String.sh
There were some minor performance bugs from To_Uppercase_String primitive function. Hence, let's fix it.
This patch fixes To_Uppercase_String primitive function bug in init/ directory.
=> init: fixed To_Uppercase_String primitive function bug

init/services/HestiaKERNEL/String/Trim_Prefix_String.ps1, init/services/HestiaKERNEL/Unicode/Trim_Prefix_Unicode.ps1, init/services/HestiaKERNEL/Unicode/Trim_Suffix_Unicode.ps1
There were some minor performance bugs from Trim_Prefix_String primitive function. Hence, let's fix it.
This patch fixes Trim_Prefix_String primitive function bug in init/ directory.
=> init: fixed Trim_Prefix_String primitive function bug

init/services/HestiaKERNEL/String/Trim_Left_String.ps1, init/services/HestiaKERNEL/String/Trim_Left_String.sh, init/services/HestiaKERNEL/Unicode/Trim_Left_Unicode.sh, init/services/HestiaKERNEL/Unicode/Trim_Right_Unicode.sh
There were some minor performance bugs from Trim_Left_String primitive function. Hence, let's fix it.
This patch fixes Trim_Left_String primitive function bug in init/ directory.
=> init: fixed Trim_Left_String primitive function bug

init/services/HestiaKERNEL/Unicode/Trim_Whitespace_Unicode.ps1, init/start.ps1, init/start.sh
To make sure we want a reliable implementations before proceeding to port any functional functions, we have to make trim_Whitespace functions to behave as it is with strict testing. Hence, let's do this.
This patch intensify trim_whitespace functions testing in init/ directory.
=> init: intensified trim_whitespace functions testing

init/services/HestiaKERNEL/String/Get_First_Character.ps1, init/services/HestiaKERNEL/String/Get_First_Character.sh, init/services/HestiaKERNEL/String/Get_Last_Character.ps1, init/services/HestiaKERNEL/String/Get_Last_Character.sh
Since the existing primitive functions for String and Unicode data types can be cascading, we should optimize them now before propogating further. Hence, let's do this.
This patch opmitizes all String and Unicode primitive functions in init/ directory.
=> init: optimized all String and Unicode primitive functions

init/services/HestiaKERNEL/String/Index_Left_String.sh, init/services/HestiaKERNEL/String/Trim_Prefix_String.ps1, init/services/HestiaKERNEL/String/Trim_Prefix_String.sh, init/services/HestiaKERNEL/Unicode/Trim_Prefix_Unicode.ps1, init/services/HestiaKERNEL/Unicode/Trim_Prefix_Unicode.sh
There were some new optimization discovered when implementing Index_Left_{String,Unicode} functions. Hence, let's backport those changes back to its predecessor Trim_Prefix_{String,Unicode}.
This patch backports changes to Trim_Prefix_{String,Unicode} primitive functions in init/ directory.
=> init: backported changes to Trim_Prefix_* primitive functions

init/services/HestiaKERNEL/String/Trim_Left_String.ps1, init/services/HestiaKERNEL/String/Trim_Left_String.sh, init/services/HestiaKERNEL/Unicode/Trim_Left_Unicode.ps1, init/services/HestiaKERNEL/Unicode/Trim_Left_Unicode.sh
There were some new optimization discovered when implementing Index_Left_{String,Unicode} functions. Hence, let's backport those changes back to its predecessor Trim_Suffix_{String,Unicode}.
This patch backports changes to Trim_Left_{String,Unicode} primitive functions in init/ directory.
=> init: backported changes to Trim_Left_* primitive functions

init/services/HestiaKERNEL/String/Trim_Right_String.ps1, init/services/HestiaKERNEL/String/Trim_Right_String.sh, init/services/HestiaKERNEL/Unicode/Trim_Right_Unicode.ps1, init/services/HestiaKERNEL/Unicode/Trim_Right_Unicode.sh
There were some new optimization discovered when implementing Index_Right_{String,Unicode} functions. Hence, let's backport those changes back to its predecessor Trim_Right_{String,Unicode}.
This patch backports changes to Trim_Right_{String,Unicode} primitive functions in init/ directory.
=> init: backported changes to Trim_Right_* primitive functions

init/services/HestiaKERNEL/String/Trim_Whitespace_Left_String.ps1, init/services/HestiaKERNEL/String/Trim_Whitespace_Left_String.sh
There were some new optimization discovered when implementing Trim_Whitespace_Right_{String,Unicode} functions. Hence, let's backport those changes back to its predecessor
Index_Left_{String,Unicode}.
This patch backports changes to Trim_Whitespace_Right_{String,Unicode} primitive functions in init/ directory.
=> init: backported changes to Trim_Whitespace_Right_* primitive functions

init/services/HestiaKERNEL/String/Trim_Whitespace_String.ps1, init/services/HestiaKERNEL/String/Trim_Whitespace_String.sh
There were some new optimization discovered when implementing Index_Right_{String,Unicode} functions. Hence, let's backport those changes back to its predecessor Trim_Whitespace_{String,Unicode}.
This patch backports changes to Trim_Whitespace_{String,Unicode} primitive functions in init/ directory.
=> init: backported changes to Trim_Whitespace_* primitive functions

init/services/HestiaKERNEL/String/Replace_Left_String.ps1, init/services/HestiaKERNEL/String/Replace_Left_String.sh, init/services/HestiaKERNEL/Unicode/Replace_Left_Unicode.ps1, init/services/HestiaKERNEL/Unicode/Replace_Left_Unicode.sh, init/start.ps1, init/start.sh
Since there are a number of level 1 libraries using the string function, we have to port its primitive ones into HestiaKERNEL library. Let's do this.
This patch ports Replace_Left_{String,Unicode} primitive function into HestiaKERNEL library into init/ directory.
=> init: ported Replace_Left_{String,Unicode} primitive function

init/services/HestiaKERNEL/Unicode/Replace_Left_Unicode.ps1, init/services/HestiaKERNEL/Unicode/Replace_Left_Unicode.sh, init/services/HestiaKERNEL/Unicode/Replace_Right_Unicode.sh
There were some functional errors discovered in Replace_Right_Unicode functions implementations. Hence, let's backport them back to Replace_Left_Unicode variants.
This patch backports Replace_Right_Unicode corrections to Replace_Left_Unicode within string components of HestiaKERNEL inside init/ directory.
=> init: backported Replace_Right_Unicode corrections to Left functions
